- name: Create metadata directory for IdP metadata
  file: name=/etc/shibboleth/metadata state=directory

- name: Enable modules shib2
  apache2_module: name={{ item }} state=present
  with_items:
    - headers
    - alias
    - include
    - negotiation
    - ssl
    - shib2

- name: Install SP Virtualhost configuration
  template:
    src: roles/{{ role_name }}/templates/sp.conf
    dest: /etc/apache2/sites-available/{{ sp_fqdn }}.conf

- name: Site content for {{ sp_fqdn }}
  copy:
    src: roles/{{ role_name }}/files/webroot/sp.example.org/
    dest: /var/www/html/{{ sp_fqdn }}/

- name: Parse {{ sp_fqdn }} in index.html
  template:
    src: roles/{{ role_name }}/files/webroot/sp.example.org/index.html
    dest: /var/www/html/{{ sp_fqdn }}/index.html

- name: Create CSS directory for SP webserver
  file: name=/var/www/css state=directory 

- name: Install Bootstrap Min CSS 
  copy:
    src: roles/{{ role_name }}/files/webroot/bootstrap.min.css
    dest: /var/www/css/bootstrap.min.css

- name: Enable SP Virtualhost
  command: a2ensite {{ sp_fqdn }}.conf
  args:
    creates: /etc/apache2/sites-enabled/{{ sp_fqdn }}.conf

- name: Restart Apache2
  service: name=apache2 state=restarted enabled=yes
