# Servlet
- name: Stop Jetty
  service: name=jetty state=stopped enabled=false
  ignore_errors: yes

- name: Uninstall jetty
  file: path="{{ jetty_path }}/" state=absent

- name: Remove /etc/init.d/jetty
  file: path=/etc/init.d/jetty state=absent

- name: Stop Tomcat
  service: name="{{ tomcat_version }}" state=stopped enabled=false
  ignore_errors: yes

- name: Uninstall Tomcat
  apt: name="{{ tomcat_version }}" state=absent purge=yes

- name: Remove /var/lib/{{ tomcat_version }}
  file: path=/var/lib/{{ tomcat_version }} state=absent

# SHIBBOLETH IDP
- name: Cleanup Shibboleth IdP Install
  file: path="{{ idp_path }}" state=absent

# MYSQL
- name: "Destroy database {{ idp_rdbms_dbname }}"
  shell: 'mysql -u {{ idp_rdbms_user }} --password={{ idp_rdbms_pw }} -e "DROP DATABASE IF EXISTS {{ idp_rdbms_dbname }}"'
  ignore_errors: yes

- name: Stop mysql-server
  service: name=mysql state=stopped enabled=false
  ignore_errors: yes

# HTTPD
- name: Stop Apache2
  service: name="apache2" state=stopped enabled=false
  ignore_errors: yes

- name: Stop NginX
  service: name="nginx" state=stopped enabled=false
  ignore_errors: yes

- name: Stop Supervisor
  service: name="suopervisor" state=stopped enabled=false
  ignore_errors: yes

# CLEANUP DEPENDENCIES
# SHIBBOLETH SP
- name: Stop SP
  service: name="shibd" state=stopped enabled=false
  ignore_errors: yes

- name: Uninstall packages
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - ntp
    - expat                 # jetty req
    - libservlet3.1-java    # servlet common requirements
    - libcommons-dbcp-java  # jetty requirement
    - libcommons-pool2-java # jetty req
    - libmysql-java         # servlet req contains: /usr/share/java/mysql.jar
    - libjsonp-java         # servlet req contains: javax.json-1.0.4.jar
    - html2text
    - emacs24-nox
    - vim
    - ntp
    - apache2
    - openjdk-8-jre
    - libapache2-mod-shib2  # sp
    - shibboleth-sp2-utils  # sp
    - shibboleth-sp2-common # sp
    - libshibsp7            # sp
    - libapache2-mod-php
    - apache2-utils
    - apache2-data
    - apache2-bin
    #- nginx
    - supervisor

- name: Cleanup Apache2 Configuration
  file: path="/etc/apache2" state=absent

- name: Cleanup Shibboleth IDP Install
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ shib_setup_folder }}"
    - "{{ idp_path }}"

- name: Cleanup Shibboleth SP Install
  file: path="/etc/shibboleth" state=absent

- name: APT autoremove unused deps
  shell: apt autoremove -y

- name: Purge old logs
  file: name={{ item }} state=absent
  with_items:
    - /var/log/shibboleth
  ignore_errors: true

- name: Stop Nginx
  service: name=nginx state=stopped

# purge nginx source installation
- name: Purge NginX installation
  file: name={{ item }} state=absent
  with_items:
    - /usr/sbin/nginx
    - /usr/sbin/nginx.old
    - /etc/nginx
    - /var/log/nginx
    - /etc/init.d/nginx
    - /etc/default/nginx
    - /etc/systemd/system/nginx.service
  ignore_errors: true
