# - name: "Uninstall and Purge"
  # include_role:
    # name: "uninstall"
  # when: uninstall == 'true'

- name: "Ensures {{ cert_path }} dir exists"
  file: path="{{ cert_path }}" state=directory

- name: "Ensures {{ cert_path }}/{{ ldap_cert }} exists"
  stat: path={{ cert_path }}/{{ ldap_cert }}
  register: ldap_cert_ok

- name: "Check {{ cert_path }}/{{ ldap_cert }}"
  fail: msg="{{ cert_path }}/{{ ldap_cert }} doesn't exists!"
  when: not ldap_cert_ok.stat.exists
  
- name: Update apt cache
  # apt: update_cache=yes
  apt: update_cache=yes cache_valid_time=86400

- name: Install common apt packages
  apt: name={{ item }} state=present
  with_items:
    - git
    - wget
    - ntp
    - emacs24-nox
    - vim
    - ntp

#  when: httpd == "apache"
#  when: httpd == "nginx"
#  when: servlet_container == "tomcat"
  
- name: Configure /etc/hosts
  template: 
    src: roles/common/templates/hosts 
    dest: /etc/hosts

- name: Copy certs
  copy: 
    src: "{{ item }}"
    dest: "{{ cert_path }}/"
    owner: root
    group: ssl-cert
    mode: 640
  with_fileglob:
    - roles/common/files/certs/*

- name: "Ensures {{ tmp_upload_dir }} dir exists"
  file: path="{{ tmp_upload_dir }}" state=directory
